{
 "title": "Prometheus-OpenWeatherMap-Exporter",
 "description": "A Dashboard for Weather data scraped via Prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "label": "City",
    "query": {
     "query": "label_values(temperature_current_celsius,city)"
    }
   },
   { "name": "temp_threshold", "label": "Temperature Threshold", "query": "5" }
  ]
 },
 "panels": [
  {
   "title": "Top 10% hottest cities",
   "type": "timeseries",
   "description": "Shows the Top 10% scraped temperatures ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "topk(\r\n  scalar(clamp_min(count(temperature_current_celsius) * 0.1, 1)),\r\n  temperature_current_celsius\r\n)",
     "legendFormat": "{{city}}"
    }
   ]
  },
  { "title": "$city", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "city" },
  {
   "title": "Current Temp vs Forecast",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperature_current_celsius{city=\"$city\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "temperature_forecast_celsius{city=\"$city\"} offset 4h",
     "legendFormat": "Forecast"
    }
   ]
  },
  {
   "title": "Rain in mm/h",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mm/h" } },
   "targets": [
    {
     "expr": "rain_current_mmh{city=\"$city\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "rain_forecast_mmh{city=\"$city\"} offset 4h",
     "legendFormat": "Forecast"
    }
   ]
  },
  {
   "title": "Temp above threshold",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperature_current_celsius{city=\"$city\"} > $temp_threshold",
     "legendFormat": "Temperature"
    }
   ]
  }
 ]
}